from cueforge.metadata.hints import (
    build_hint_candidates,
    extract_cover_hints,
    extract_credit_hints,
    extract_metadata_hints,
    preferred_theme_types,
)


def test_extract_japanese_ending_theme_from_next_line() -> None:
    hints = extract_metadata_hints(
        {
            "description": "▮エンディングテーマ\nナナヲアカリ「明日の私に幸あれ」\n\n▮スタッフ\n監督：長澤剛"
        }
    )

    assert len(hints) == 1
    assert hints[0].context == "エンディングテーマ"
    assert hints[0].metadata.artist == "ナナヲアカリ"
    assert hints[0].metadata.title == "明日の私に幸あれ"
    assert hints[0].metadata.genre == "Anison"


def test_extract_japanese_opening_theme_from_same_line() -> None:
    hints = extract_metadata_hints({"description": "▮オープニングテーマ 310「パーフェクトデイ」"})

    assert len(hints) == 1
    assert hints[0].metadata.artist == "310"
    assert hints[0].metadata.title == "パーフェクトデイ"


def test_build_hint_candidate_records_provenance() -> None:
    candidates = build_hint_candidates({"description": 'Ending Theme: "Song Title" by Artist Name (eps 1-12)'})

    assert candidates[0].provider == "description_ending_theme"
    assert candidates[0].metadata.title == "Song Title"
    assert candidates[0].metadata.artist == "Artist Name"
    assert candidates[0].raw["source"] == "description"


def test_build_hint_candidates_prefers_ending_when_video_title_says_ending() -> None:
    candidates = build_hint_candidates(
        {
            "title": "ノンクレジットエンディング映像",
            "description": "▮オープニングテーマ\n310「パーフェクトデイ」\n▮エンディングテーマ\nナナヲアカリ「明日の私に幸あれ」",
        }
    )

    assert len(candidates) == 1
    assert candidates[0].metadata.artist == "ナナヲアカリ"
    assert candidates[0].metadata.title == "明日の私に幸あれ"
    assert preferred_theme_types({"title": "ノンクレジットエンディング映像"}) == {"ED"}


def test_ignores_auto_generated_youtube_description_with_quoted_featured_artist() -> None:
    candidates = build_hint_candidates(
        {
            "description": 'Provided to YouTube by HARDCORE TANO*C\n\n'
            'Dear Mother Father (feat. DD"ナカタ"Metal) · RoughSketch · DD"Nakata"Metal\n\n'
            'Dear Mother Father (feat. DD"Nakata"Metal)\n\n'
            "Auto-generated by YouTube."
        }
    )

    assert candidates == []


def test_ignores_auto_generated_youtube_description_with_composer_credit() -> None:
    candidates = build_hint_candidates(
        {
            "title": "アオクナレ (feat. DJ'TEKINA / /SOMETHING)",
            "artist": "RumBlue from LiveRevolt, DJ'TEKINA / /SOMETHING",
            "description": "Provided to YouTube by TOKYO LOGIC\n\n"
            "アオクナレ (feat. DJ'TEKINA / /SOMETHING) · RumBlue from LiveRevolt · DJ'TEKINA / /SOMETHING\n\n"
            "Gekijyou Blue Future / Aokunare\n\n"
            "Released on: 2017-12-07\n\n"
            "Lyricist: Machigerita\n"
            "Composer: DJ'TEKINA / /SOMETHING\n\n"
            "Auto-generated by YouTube.",
        }
    )

    assert candidates == []


def test_extracts_official_mv_quoted_song_from_title() -> None:
    candidates = build_hint_candidates(
        {
            "title": "ano「ちゅ、多様性。」Music Video",
            "release_date": "20221124",
            "webpage_url": "https://www.youtube.com/watch?v=-lec--FlSJ4",
        }
    )

    assert candidates[0].provider == "title_quoted_song"
    assert candidates[0].metadata.artist == "ano"
    assert candidates[0].metadata.title == "ちゅ、多様性。"
    assert candidates[0].metadata.release_date == "2022-11-24"


def test_extracts_title_first_quoted_song_from_user_upload_title() -> None:
    candidates = build_hint_candidates(
        {
            "title": "「コネクト」ClariS Full",
            "uploader": "雪絵今関",
            "upload_date": "20170105",
            "webpage_url": "https://www.youtube.com/watch?v=HcYN5Gn5IuM",
        }
    )

    assert candidates[0].provider == "title_quoted_song"
    assert candidates[0].metadata.artist == "ClariS"
    assert candidates[0].metadata.title == "コネクト"
    assert candidates[0].metadata.release_date == "2017-01-05"


def test_extracts_compact_artist_title_from_user_upload_title() -> None:
    candidates = build_hint_candidates(
        {
            "title": "린-개미관찰",
            "uploader": "윤다희",
            "upload_date": "20140427",
            "webpage_url": "https://www.youtube.com/watch?v=Jty1MDOAKvQ",
        }
    )

    assert candidates[0].provider == "title_artist_title"
    assert candidates[0].metadata.artist == "린"
    assert candidates[0].metadata.title == "개미관찰"
    assert candidates[0].metadata.release_date == "2014-04-27"


def test_extracts_cover_song_from_title_tail_and_uses_channel_performer() -> None:
    candidates = build_hint_candidates(
        {
            "title": "체인소맨 레제편 그 노래 / IRIS OUT - 요네즈 켄시 (COVER)",
            "channel": "계화",
            "uploader": "계화",
            "description": "Original: IRIS OUT - 米津玄師 (yonezu kenshi)",
        }
    )

    assert len(candidates) == 1
    assert candidates[0].provider == "title_cover"
    assert candidates[0].metadata.title == "IRIS OUT"
    assert candidates[0].metadata.artist == "계화"
    assert candidates[0].metadata.album_artist == "계화"
    assert candidates[0].raw["prefer_initial_metadata"] is True


def test_extracts_cover_song_before_bracket_when_performer_is_title_suffix() -> None:
    hints = extract_cover_hints(
        {
            "title": "출항 [抜錨(발묘) / 나나호시 관현악단] ㅣ아카네 리제(Akane Lize) 【COVER】",
            "channel": "아카네 리제 AKANE LIZE",
        }
    )

    assert len(hints) == 1
    assert hints[0].metadata.title == "출항"
    assert hints[0].metadata.artist == "아카네 리제"


def test_cover_video_does_not_create_ambiguous_artist_dash_title_hint() -> None:
    candidates = build_hint_candidates(
        {
            "title": "요네즈 켄시 - IRIS OUT (COVER)",
            "channel": "계화",
            "description": "Original: 米津玄師 - IRIS OUT",
        }
    )

    assert candidates == []


def test_generic_vocaloid_prefix_does_not_create_artist_title_candidate() -> None:
    candidates = build_hint_candidates(
        {
            "title": "보컬로이드 -개미관찰-",
            "uploader": "토우링고",
            "upload_date": "20140729",
            "webpage_url": "https://www.youtube.com/watch?v=7B4yU08Bs5A",
        }
    )

    assert candidates == []


def test_extracts_original_song_from_korean_translation_description() -> None:
    hints = extract_credit_hints(
        {
            "description": "ロストアンブレラ (Lost Umbrella)\n"
            "노래 : 歌愛ユキ\n"
            "작사/작곡 : 稲葉曇\n\n"
            "원본 : https://youtu.be/DeKLpgzh-qQ"
        }
    )

    assert len(hints) == 1
    assert hints[0].context == "credits"
    assert hints[0].metadata.title == "ロストアンブレラ"
    assert hints[0].metadata.artist == "稲葉曇"


def test_extracts_labeled_title_and_artist_from_description() -> None:
    hints = extract_credit_hints(
        {
            "description": "Title: Midnight Runner\n"
            "Artist: Neon Driver\n"
            "Album: Night Drive Clips\n"
            "Stream: https://example.com"
        }
    )

    assert len(hints) == 1
    assert hints[0].metadata.title == "Midnight Runner"
    assert hints[0].metadata.artist == "Neon Driver"


def test_extracts_japanese_labeled_title_and_artist_from_description() -> None:
    hints = extract_credit_hints(
        {
            "description": "曲名：透明な夜\n"
            "アーティスト：月灯り\n"
            "映像：sample"
        }
    )

    assert len(hints) == 1
    assert hints[0].metadata.title == "透明な夜"
    assert hints[0].metadata.artist == "月灯り"
